// metal_probe.cpp — isolate the BF16 function-constant lookup failure.
//
// Loads the SAME embedded MSL source that ggml-metal uses, compiles it via
// newLibraryWithSource:, then tries newFunctionWithName: (plain) and
// newFunctionWithName:constantValues: (specialized) for the BF16 kernel.
//
// Built as a pybind11 module so it runs in the SAME .so/dlopen context that
// crashes. If plain lookup fails here but succeeds in an exe, we've isolated
// the failure to "library compiled in dlopen context lacks the function".
//
// Run: python -c "import metal_probe; metal_probe.probe()"

#include <pybind11/pybind11.h>
#include <Foundation/Foundation.h>
#include <Metal/Metal.h>
#include <cstdio>

namespace py = pybind11;

// Pull the embedded MSL source straight from libggml-metal (same symbols ggml-metal uses)
extern "C" const char ggml_metallib_start[];
extern "C" const char ggml_metallib_end[];

static int probe() {
    id<MTLDevice> device = MTLCreateSystemDefaultDevice();
    if (!device) { printf("[probe] no device\n"); return 1; }
    printf("[probe] device: %s\n", [[device name] UTF8String]);

    // Use the merged MSL source file (ggml-common.h already inlined) that
    // ggml-metal's build produces — same source compiled at runtime.
    NSString * path = @"/Users/jinzhenj/MinerU-Repo/llama.cpp-build/llama.cpp/build/ggml/src/ggml-metal/autogenerated/ggml-metal-embed.metal";
    NSError * readErr = nil;
    NSString * src = [NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:&readErr];
    if (!src) { printf("[probe] failed to read merged source: %s\n", [[readErr localizedDescription] UTF8String]); return 2; }
    printf("[probe] loaded merged MSL source: %lu bytes\n", (unsigned long)[src length]);

    // Match ggml-metal's compile options (preprocessor macros)
    NSMutableDictionary * prep = [NSMutableDictionary dictionary];
    // has_bfloat is true on M1 Max
    [prep setObject:@"1" forKey:@"GGML_METAL_HAS_BF16"];
    // embed-library path inlines ggml-common.h; the #else branch has a stray include
    [prep setObject:@"1" forKey:@"GGML_METAL_EMBED_LIBRARY"];
    MTLCompileOptions * opts = [MTLCompileOptions new];
    opts.preprocessorMacros = prep;

    NSError * err = nil;
    id<MTLLibrary> lib = [device newLibraryWithSource:src options:opts error:&err];
    if (!lib) { printf("[probe] newLibraryWithSource FAILED: %s\n", [[err localizedDescription] UTF8String]); return 3; }
    printf("[probe] library compiled OK. functionNames count: %lu\n", (unsigned long)[[lib functionNames] count]);

    // Enumerate: is the BF16 base function present?
    NSArray<NSString *> * names = [lib functionNames];
    NSString * target = @"kernel_mul_mv_ext_bf16_f32_r1_2";
    bool found_plain = false;
    for (NSString * n in names) {
        if ([n isEqualToString:target]) { found_plain = true; break; }
    }
    printf("[probe] '%s' in functionNames: %s\n", [target UTF8String], found_plain ? "YES" : "NO");

    // Plain lookup (what ggml-metal does when cv==nil)
    id<MTLFunction> f_plain = [lib newFunctionWithName:target];
    printf("[probe] newFunctionWithName('%s'): %s\n", [target UTF8String], f_plain ? "OK" : "nil");

    // Specialized lookup (what ggml-metal does for bf16, cv != nil)
    MTLFunctionConstantValues * cv = [MTLFunctionConstantValues new];
    // The specialization constants for kernel_mul_mv_ext_bf16_f32_r1_2 — use
    // whatever; the point is to see if specialization returns a function or nil.
    // (We don't know exact constant names, so this may legitimately fail —
    //  but a nil here with a specific error is still informative.)
    id<MTLFunction> f_spec = [lib newFunctionWithName:target constantValues:cv error:&err];
    printf("[probe] newFunctionWithName:constantValues: %s", f_spec ? "OK" : "nil");
    if (err) printf(" (err: %s)", [[err localizedDescription] UTF8String]);
    printf("\n");

    // Also probe a known-good kernel for contrast
    NSString * good = @"kernel_get_rows_f32";
    id<MTLFunction> f_good = [lib newFunctionWithName:good];
    printf("[probe] (contrast) newFunctionWithName('%s'): %s\n", [good UTF8String], f_good ? "OK" : "nil");

    return 0;
}

PYBIND11_MODULE(metal_probe, m) {
    m.def("probe", &probe, "Probe Metal library for BF16 function lookup");
}
