from __future__ import annotations
import typing
__all__: list[str] = list()
class _EngineCore:
    def __init__(self, model_path: str, mmproj_path: str, n_ctx_seq: typing.SupportsInt | typing.SupportsIndex, n_gpu_layers: typing.SupportsInt | typing.SupportsIndex, n_parallel: typing.SupportsInt | typing.SupportsIndex, verbosity: typing.SupportsInt | typing.SupportsIndex, n_threads: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def generate(self, body: str) -> dict:
        ...
    def generate_stream(self, body: str) -> _StreamIterator:
        ...
    @property
    def eos_token_str(self) -> str:
        ...
class _StreamIterator:
    def __iter__(self) -> _StreamIterator:
        ...
    def __next__(self) -> dict:
        ...
